name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: denolib/setup-deno@master
        with:
          deno-version: 0.35.0

      - run: deno --version
      - run: deno fmt --check
      - run: deno test -A
      - run: mkdir target && deno bundle mod.ts target/mod.ts

      - name: Release
        if: startsWith(github.ref, 'refs/tags/v') && github.repository == 'zhmushan-zone/abc'
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          files: target/mod.ts
